### ISSUE TITLE
References to Client code on Server

### ISSUE THREAD

**Issue by dshadowwolf** [TheXFactor117/Levels#119]
It appears you are trying to do the right thing in not referencing deprecated code, but the non-deprecated I18n code is client-side only. Got this when crafting an axe on a server with the most recent release of Levels on Curse (3.0.0-beta):
```
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.thexfactor117.levels.leveling.Attribute.getName(Attribute.java:145) ~[Attribute.class:?]
        at com.thexfactor117.levels.leveling.Attribute.addAttribute(Attribute.java:111) ~[Attribute.class:?]
        at com.thexfactor117.levels.util.WeaponHelper.getRandomizedAttributes(WeaponHelper.java:168) ~[WeaponHelper.class:?]
        at com.thexfactor117.levels.util.WeaponHelper.create(WeaponHelper.java:64) ~[WeaponHelper.class:?]
        at com.thexfactor117.levels.event.EventCreateWeapon.create(EventCreateWeapon.java:62) ~[EventCreateWeapon.class:?]
        at com.thexfactor117.levels.event.EventCreateWeapon.onPlayerTick(EventCreateWeapon.java:37) ~[EventCreateWeapon.class:?]
```

**Comment by Cntrldfusion** [comment]
Same here, causes a server crash every time. 

[crash-2017-05-10_12.49.41-server.txt](https://github.com/TheXFactor117/Levels/files/990705/crash-2017-05-10_12.49.41-server.txt)
[crash-2017-05-10_12.51.21-server.txt](https://github.com/TheXFactor117/Levels/files/990707/crash-2017-05-10_12.51.21-server.txt)
[crash-2017-05-10_12.53.34-server.txt](https://github.com/TheXFactor117/Levels/files/990708/crash-2017-05-10_12.53.34-server.txt)
[crash-2017-05-10_12.55.19-server.txt](https://github.com/TheXFactor117/Levels/files/990706/crash-2017-05-10_12.55.19-server.txt)

**Comment by Nachtflame** [comment]
For me, it's not causing a server crash, just dumping the client every time they connect until I delete their player data.

**Comment by Terpo** [comment]
As far as I can see it also is kind of game breaking when its getting fixed. Problem is, that the localized name is saved as the nbt value. Somehow you have to split your getName calls. One that only shows up when the client is displaying the tooltip and one that is used for everything else on server side. I really hope this can be fixed in the near future. For now I deactivated the mod on the server. :(

**Comment by TheXFactor117** [comment]
Ah that's my fault. I'll fix this.

**Comment by TheXFactor117** [comment]
This should be fixed now.

**Comment by Terpo** [comment]
There is still something wrong: https://gist.githubusercontent.com/Terpo/a820b1a6c81ec3f2c463d11141836a7b/raw/4ef5c9f1e73afabee323afb94640e87941d9ec2f/gistfile1.txt

Search for:
Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@327c4918:
java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
at com.thexfactor117.levels.util.WeaponHelper.setAttributeModifiers(WeaponHelper.java:107) ~[WeaponHelper.class:?]
at com.thexfactor117.levels.util.WeaponHelper.create(WeaponHelper.java:67) ~[WeaponHelper.class:?]
at com.thexfactor117.levels.event.EventCreateWeapon.create(EventCreateWeapon.java:62) ~[EventCreateWeapon.class:?]
at com.thexfactor117.levels.event.EventCreateWeapon.onPlayerTick(EventCreateWeapon.java:37) ~[EventCreateWeapon.class:?]
