### ISSUE TITLE
Crash when fighting mobs

### ISSUE THREAD

**Issue by bculkin2442** [TheXFactor117/Levels#21]
When fighting a skeleton, the game crashed with the following exception

java.lang.ClassCastException: net.minecraft.entity.monster.EntitySkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
	at com.thexfactor117.levels.events.EventLivingHurt.hitEntity(EventLivingHurt.java:273)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_284_EventLivingHurt_hitEntity_LivingHurtEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:298)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1129)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54)
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:270)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

The full log file is not attached at the moment, because it is a large file, but if you need it I can get it to you somehow.

**Comment by bculkin2442** [comment]
If you could cancel this, it would be nice. I was using an old version and the new version looks like its fixed this bug.
