### ISSUE TITLE
Randomly crashes - Possibly trying to level up TiCo?

### ISSUE THREAD

**Issue by 100photos** [TheXFactor117/Levels#48]
```[09:41:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.thexfactor117.levels.leveling.AbilitySelection.getRandomizedAbilities(AbilitySelection.java:38) ~[AbilitySelection.class:?]
        at com.thexfactor117.levels.leveling.Experience.getNextLevel(Experience.java:66) ~[Experience.class:?]
        at com.thexfactor117.levels.events.EventLivingHurt.hitEntity(EventLivingHurt.java:697) ~[EventLivingHurt.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_481_EventLivingHurt_hitEntity_LivingHurtEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:504) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.applyModDamage(EntityLivingBase.java:59) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.damageEntityHook(EntityLivingBase.java:538) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:427) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543) ~[lu.class:?]
        at net.minecraft.entity.boss.EntityDragon.func_70971_b(EntityDragon.java:452) ~[xb.class:?]
        at net.minecraft.entity.boss.EntityDragon.func_70636_d(EntityDragon.java:314) ~[xb.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:150) ~[TrackingUtil.class:1.10.2-2171-5.1.0-BETA-1992]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjl000(WorldServer.java:1310) ~[ls.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:85) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) ~[ls.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1237) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more
```

I think this happens when it tries to level up a weapon/armor piece, but its odd because I dont think I was even swinging when the server crashed. I'll have to remove it I guess, but I want it to work so badly.
I noticed there was an incompatibility with TiCo noted on the curseforge page, and I was using a cleaver, so maybe that's it. One "solution" ( idk if its possible ) could be to make a weapon/armor/mod blacklist in the config folder for levels. Anyway, if you need the modlist I can get it for you. Thanks.

**Comment by TheXFactor117** [comment]
Thanks for reporting. I'm in the middle of re-writing the mod, so I won't be able to post a fixed build unfortunately. I will however make sure this is fixed in the new version. Sorry for any inconveniences!

**Comment by ChipWolf** [comment]
Hey @TheXFactor117, got a timescale for us by chance? We're tracking this issue hot in Resonant Rise 4, users are getting antsy ;)

![](https://i.cwlf.uk/AJ7K)

**Comment by TheXFactor117** [comment]
I will have a beta version of the new mod released soon. Unfortunately it won't have all the features I would like, but it should spur on development when I do release the first version.

**Comment by TheXFactor117** [comment]
I actually think the issue could possibly be fixed already. One of the changes I made in the new version of the mod was removing randomized abilities, opting for the player to choose which ability they want rather. The code causing the problem right now was the randomization code which isn't in the mod anymore. This won't guarantee that there is no more problem, but chances are it could be fixed.

Keep a look out for the new beta releasing shortly. If the issue persists, open up a new issue with the new information.
