### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by FuriousXtremes** [TheXFactor117/Levels#81]
When I installed this mod into my server, I get this crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  MMFMLCorePlugin (MultiMine-1.11.2.jar)
  LoadingPlugin (Quark-r1.2-77.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/26/17 2:13 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Levels (levels)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:94)
	at com.thexfactor117.levels.init.ModEvents.registerEvents(ModEvents.java:38)
	at com.thexfactor117.levels.Levels.preInit(Levels.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4c5474f5 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 39 more
Caused by: java.lang.RuntimeException: Attempted to load class bes for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 336876784 bytes (321 MB) / 794296320 bytes (757 MB) up to 1895825408 bytes (1808 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226-universal.jar) 
	UCH	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226-universal.jar) 
	UCH	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCH	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCH	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCH	actuallyadditions{1.11.2-r99} [Actually Additions] (ActuallyAdditions-1.11.2-r99.jar) 
	UCH	advancedcombat{1.0.1} [Advanced Combat] (advancedcombat-1.0.1-[1.11.2].jar) 
	UCH	animalbikes{1.11.2} [Animal Bikes] (AnimalBikes_1.11.2(24jan17).jar) 
	UCH	thedragonlib{1.11.2-2.1.0} [TheDragonLib] (thedragonlib-1.11.2-2.1.0.jar) 
	UCH	armorplus{1.11.2-9.5.2.3-beta} [ArmorPlus] (armorplus-1.11.2-9.5.2.3-beta.jar) 
	UCH	quark{r1.2-77} [Quark] (Quark-r1.2-77.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	cdm{0.0.2} [MrCrayfish's Device Mod] (cdm-0.0.2-alpha-mc1.11.jar) 
	UCH	cfm{4.1.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.11.2.jar) 
	UCH	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCH	charsetlib{0.4.0-pre7} [?] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetpipes{0.4.0-pre7} [|] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsettweaks{0.4.0-pre7} [*] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetstorage{0.4.0-pre7} [?] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetcarts{0.4.0-pre7} [?] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetcrafting{0.4.0-pre7} [#] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetdecoration{0.4.0-pre7} [^] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	charsetwrench{0.4.0-pre7} [/] (Charset-mc1.11.2-0.4.0-pre7-20658a07251e171c.jar) 
	UCH	chesttransporter{2.6.0} [Chest Transporter] (ChestTransporter-1.11-2.6.0.jar) 
	UCH	cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.11] (cnoapm-mcv1.11.jar) 
	UCH	eleccore{1.6.381} [ElecCore] (ElecCore-1.11-1.6.381.jar) 
	UCH	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.11-1.4.109.jar) 
	UCH	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCH	cyclicmagic{1.0.0} [Cyclic] (Cyclic-1.11.2-1.0.0.jar) 
	UCH	cyclopscore{0.9.1} [Cyclops Core] (CyclopsCore-1.11.2-0.9.1.jar) 
	UCH	everlastingabilities{1.2.4} [EverlastingAbilities] (EverlastingAbilities-1.11.2-1.2.4.jar) 
	UCH	excore{2.0.0-alpha7-1.11.2} [EXCore] (EXCore-2.0.0-alpha7-1.11.2.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.2.0.jar) 
	UCH	zerocore{1.11.2-0.1.0.2} [Zero CORE] (zerocore-1.11.2-0.1.0.2.jar) 
	UCH	bigreactors{1.11.2-0.4.5.25} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.25.jar) 
	UCH	fei{1.1.0-alpha2-1.11.2} [Forever Enough Items] (Forever-Enough-Items-1.1.0-alpha2-1.11.2.jar) 
	UCH	grimpack{4.0.0.0-beta} [Grim Pack] (Grim Pack-1.11.2-4.0.0.0-beta.jar) 
	UCH	waila{1.8.7} [Waila] (Hwyla-1.8.7-B21_1.11.jar) 
	UCH	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCH	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
	UCH	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCH	jrftl{1.1} [jrftl] (JRFTL-1.1.jar) 
	UCE	levels{b2.2.0} [Levels] (Levels 2-1.11.2-b2.2.0.jar) 
	UCH	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	metamorph{1.0.2} [Metamorph] (metamorph-1.0.2-1.11.jar) 
	UCH	morefurnaces{1.9.4} [More Furnaces] (MoreFurnaces-1.11-1.9.4.jar) 
	UCH	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
	UCH	multibeds{1.3.1} [Multi-Beds] (multibeds-1.11.0-1.3.1.jar) 
	UCH	multimine{1.5.6} [Multi Mine] (MultiMine-1.11.2.jar) 
	UCH	mysticalagriculture{1.3.9} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.9.jar) 
	UCH	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCH	harvestcraft{1.11.2b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2b.jar) 
	UCH	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCH	refinedstorage{1.3.5} [Refined Storage] (refinedstorage-1.3.5.jar) 
	UCH	roots{0.009} [Roots 2] (roots-2-0.009.jar) 
	UCH	switchbow{1.0} [Switch-Bow] (switchbow-1.0.jar) 
	UCH	thermalsolars{1.11.2 Beta V1.2} [Thermal Solars] (thermalsolars-1.11.2-1.2.jar) 
	UCH	thutcore{4.3.1} [ThutCore] (thutcore-4.3.1.jar) 
	UCH	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCH	vanillanethermetals{1.1} [Vanilla Nether Metals] (VanillaNetherMetals-[1.11]-1.1.jar) 
	UCH	wearablebackpacks{2.0.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.0.0.jar) 
	UCH	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  shetiphian.core.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
MMFMLCorePlugin (MultiMine-1.11.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (Quark-r1.2-77.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TheXFactor117** [comment]
I'll look into and will fix it soon. Thanks!

**Comment by TheXFactor117** [comment]
Will be fixed in the next version.
